package esp.svc.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-19T10:10:18.623-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://hello.svc.esp/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://hello.svc.esp/", className = "esp.svc.hello.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://hello.svc.esp/", className = "esp.svc.hello.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
