
package esp.svc.hello;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import esp.svc.impl.ejb.HelloBeanService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-19T10:10:18.596-05:00
 * Generated source version: 3.2.1
 * 
 */
public final class HelloService_HelloServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ejb.impl.svc.esp/", "HelloBeanService");

    private HelloService_HelloServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloBeanService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloBeanService ss = new HelloBeanService(wsdlURL, SERVICE_NAME);
        HelloService port = ss.getHelloServicePort();  
        
        {
        System.out.println("Invoking hello...");
        java.lang.String _hello_arg0 = "";
        java.lang.String _hello__return = port.hello(_hello_arg0);
        System.out.println("hello.result=" + _hello__return);


        }

        System.exit(0);
    }

}
