package esp.svc.calc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-19T10:10:18.266-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://calc.svc.esp/", name = "CalculatorService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculatorService {

    @WebMethod
    @RequestWrapper(localName = "calculate", targetNamespace = "http://calc.svc.esp/", className = "esp.svc.calc.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://calc.svc.esp/", className = "esp.svc.calc.CalculateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public esp.svc.calc.CalculateResult calculate(
        @WebParam(name = "calculateRequest", targetNamespace = "")
        esp.svc.calc.CalculateRequest calculateRequest
    ) throws CalculatorException_Exception;
}
