
package esp.svc.calc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import esp.svc.impl.ejb.CalculatorBeanService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-19T10:10:18.152-05:00
 * Generated source version: 3.2.1
 * 
 */
public final class CalculatorService_CalculatorServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ejb.impl.svc.esp/", "CalculatorBeanService");

    private CalculatorService_CalculatorServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculatorBeanService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalculatorBeanService ss = new CalculatorBeanService(wsdlURL, SERVICE_NAME);
        CalculatorService port = ss.getCalculatorServicePort();  
        
        {
        System.out.println("Invoking calculate...");
        esp.svc.calc.CalculateRequest _calculate_calculateRequest = null;
        try {
            esp.svc.calc.CalculateResult _calculate__return = port.calculate(_calculate_calculateRequest);
            System.out.println("calculate.result=" + _calculate__return);

        } catch (CalculatorException_Exception e) { 
            System.out.println("Expected exception: CalculatorException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
