
package esp.svc.calc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-19T10:10:18.255-05:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "CalculatorException", targetNamespace = "http://calc.svc.esp/")
public class CalculatorException_Exception extends Exception {
    
    private esp.svc.calc.CalculatorException calculatorException;

    public CalculatorException_Exception() {
        super();
    }
    
    public CalculatorException_Exception(String message) {
        super(message);
    }
    
    public CalculatorException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CalculatorException_Exception(String message, esp.svc.calc.CalculatorException calculatorException) {
        super(message);
        this.calculatorException = calculatorException;
    }

    public CalculatorException_Exception(String message, esp.svc.calc.CalculatorException calculatorException, Throwable cause) {
        super(message, cause);
        this.calculatorException = calculatorException;
    }

    public esp.svc.calc.CalculatorException getFaultInfo() {
        return this.calculatorException;
    }
}
