	package esp.svc.impl.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import esp.svc.calc.CalculatorService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-19T10:10:18.275-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "CalculatorBeanService", 
                  wsdlLocation = "file:/D:/pers_proj/esp-ejb-bundle/esp-ejbws-stub/src/main/resources/ejbws-wsdl/openejb/Calculator_ejbws_openejb.wsdl",
                  targetNamespace = "http://ejb.impl.svc.esp/") 
public class CalculatorBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ejb.impl.svc.esp/", "CalculatorBeanService");
    public final static QName CalculatorServicePort = new QName("http://ejb.impl.svc.esp/", "CalculatorServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/pers_proj/esp-ejb-bundle/esp-ejbws-stub/src/main/resources/ejbws-wsdl/openejb/Calculator_ejbws_openejb.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculatorBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/pers_proj/esp-ejb-bundle/esp-ejbws-stub/src/main/resources/ejbws-wsdl/openejb/Calculator_ejbws_openejb.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculatorBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculatorBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CalculatorBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculatorBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculatorBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort() {
        return super.getPort(CalculatorServicePort, CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort(WebServiceFeature... features) {
        return super.getPort(CalculatorServicePort, CalculatorService.class, features);
    }

}
